export const tabConfig = [{
    icon: '&#xe660;',
    name: "首页",
    key: 'home',
    src: `${weex.config.eros.jsServer}/dist/js/pages/yanxuanDemo/home/index.js`,
    visibility: 'visible'
}, {
    icon: '&#xe65c;',
    name: "发现",
    key: 'topic',
    src: `${weex.config.eros.jsServer}/dist/js/pages/yanxuanDemo/topic/index.js`,
    visibility: 'hidden'
}, {
    icon: '&#xe66a;',
    name: "目的地",
    key: 'class',
    src: `${weex.config.eros.jsServer}/dist/js/pages/yanxuanDemo/class/index.js`,
    visibility: 'hidden'
}, {
    icon: '&#xe69d;',
    name: "行程",
    key: 'shop',
    src: `${weex.config.eros.jsServer}/dist/js/pages/yanxuanDemo/shop/index.js`,
    visibility: 'hidden'
}, {
    icon: '&#xe639;',
    name: "我的",
    key: 'my',
    src: `${weex.config.eros.jsServer}/dist/js/pages/yanxuanDemo/my/index.js`,
    visibility: 'hidden'
}]